name: Todoist Syncer

on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: "0 */4 * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aldoyh/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{secrets.TODOIST_API_KEY}}
          PREMIUM: ""
        # Notify on Slack
      - uses: act10ns/slack@v2.0.0
        with:
          # Specify Slack Incoming Webhook URL
          status: "Success"
          # Report on the status of individual steps
          # steps: # optional
          # Override default channel with different channel or username
          channel: "github-live"
          # Override message format for step

      - name: First interaction
        uses: actions/first-interaction@v1.1.1
        with:
          # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: ${{secrets.GITHUB_TOKEN}}
          # Comment to post on an individual's first issue
          issue-message: "Hello, thanks for posting."
          # Comment to post on an individual's first pull request
          pr-message: "Approved ❤️"

      - name: slack-send
          # Slack bot token
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel ID where message will be posted. Needed if using bot token
          channel-id: "github-pushed"
          # Message to post into Slack. Needed if using bot token
          slack-message: "Pushed now!"
          # JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead
          payload: ""
          # path to JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead. If payload is provided, it will take preference over this field
          payload-file-path: ""
          # The timestamp of a previous message posted. It will update the existing message instead of posting a new message
          update-ts: ""
